# This is a basic workflow to help you get started with Actions

name: Coverage Check

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the main branch

  push:
    branches: [ main ]
    
  pull_request:
    branches: [main]
    
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - run: npm install
        
      - run: npm run coverage
      
     # - run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r "coverage/lcov.info"
       # env: 
       #   CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
          
      - name: Generate Code Coverage report
        uses: barecheck/code-coverage-action@v0.5.1
        with:
          barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
          lcov-file: "./coverage/lcov.info"
          base-lcov-file: "./lcov.info"
          minimum-ratio: 0 # Fails Github action once code coverage is decreasing
          send-summary-comment: true
          show-annotations: "warning" # Possible options warning|error
        
      
